db.options:
    driver:   pdo_mysql
    dbname:     digex
    host:     localhost
    user:     root
    password: null

em.entities: [src/Digitas/Demo/Entity]
em.fixtures:  [src/Digitas/Demo/DataFixtures/ORM]


locale_fallback: 'fr'

# if you want to restrict unknown locale
locales_allowed: [en, fr]

security.firewalls:
    unsecured:
      pattern: '^/admin/login$'
      anonymous: true
    admin:
      pattern: '^/admin'
      form:
        login_path: '/admin/login'
        check_path: '/admin/login_check'
      logout:
        logout_path: '/admin/logout'
      users:
        'admin': [ROLE_ADMIN, 5FZ2Z8QIkA7UTZ4BYkoC+GsReLf569mSKDsfods6LYQ8t+a8EW9oaircfMpmaLbPBh4FOBiiFyLfuZmTSUwzZg==]

security.role_hierarchy:
    'ROLE_ADMIN': ['ROLE_USER', 'ROLE_ALLOWED_TO_SWITCH']